### ISSUE TITLE
Test the equivalency of triangles in our python tripcolor vs. in the data set.

### ISSUE THREAD

**Issue by mathieuslplante** [a-bouchat/ice-tracker-deformations#10]
verify that there is no error in the script that reconstruct the lat-lon vectors used to define the triangle indices.

This could be done by running the dataset for 1 day, and compare the output image to the one we produce with the netcdf tool.

**Comment by a-bouchat** [comment]
Visuellement ça semble être équivalent, mais on pourrait vérifier peut-être plus en détails autrement?
<img width="1278" alt="Screen Shot 2023-02-01 at 11 46 49 AM" src="https://user-images.githubusercontent.com/107127837/216109790-19ff016b-f97e-4a82-b1df-ec82329d567a.png">

**Comment by dringeis** [comment]
I think it looks good and we can close this issue. 
If they were a problem it would probably mess up the whole plot.
