### ISSUE TITLE
Comparison of coverage with Howell 2022

### ISSUE THREAD

**Issue by mathieuslplante** [a-bouchat/ice-tracker-deformations#18]
We have questions about the coverage differences between what they have in the paper and what we have. 

We could try to reproduce the coverage figures from their paper and see if we can have a chat with Mike and Stephen about this.

**Comment by dringeis** [comment]
![RCMS1_20200311_20200317_dt72_tol72_res20_int24_coverage_area_map](https://user-images.githubusercontent.com/30409025/219085670-580c39ae-334b-49dc-a167-cd12651fbc95.png)

We have to keep in mind that the figure in Howel et al 2020 probably only shows single images and not overlaps

**Comment by mathieuslplante** [comment]
Yes makes sense. In that way, that works well with the coverage we have, and the fact that we have half the number of pair files.

I believe that this settles the case then?
