### ISSUE TITLE
Add triangle area to netcdf

### ISSUE THREAD

**Issue by a-bouchat** [a-bouchat/ice-tracker-deformations#23]
... and then redo area time series function to compute directly from the sum of triangle areas from the netcdf.

**Comment by a-bouchat** [comment]
I realized that we cannot simply compute the sum of the triangle areas to make the area time series because of overlapping triangles... so maybe it is better to stay with the map binning for now as a sufficient estimate of the area covered by the data set.

**Comment by mathieuslplante** [comment]
Yes, I think the way you did it is the best. 
I guess we can close this issue?

**Comment by a-bouchat** [comment]
I am still adding the triangle area to the netcdf because we will need it to characterize the spatial scale of the deformation estimates. I will close this issue when I do the PR.
