### ISSUE TITLE
Find how to open files of RCM new

### ISSUE THREAD

**Issue by dringeis** [a-bouchat/ice-tracker-deformations#26]

**Comment by mathieuslplante** [comment]
I open it with panda as a .csv file, and cut the lines that are making the file not readable as a dataset. 
I also added statements to read the dates from the different nomenclature. This is not done the best way (by if statements in the code, not in functions). This could be simplified when we create file classes and data objects in the code.

**Comment by mathieuslplante** [comment]
This will be part of my next merge request.
