### ISSUE TITLE
Comparison with higher resolution of A. Komarov

### ISSUE THREAD

**Issue by mathieuslplante** [a-bouchat/ice-tracker-deformations#32]
Based on our description of the deformation uncertainties associated with the pixel resolution of 200m, Alex started to run the ice tracker with higher resolution (80m).

This issue is to take a look at the differences between this set of data and what we have from the operational ice tracker.

**Comment by mathieuslplante** [comment]
The coverage from Alex's data is much, much better than those we already have:
![2022_dec_v1_vs_v2](https://user-images.githubusercontent.com/51676669/221282931-c619faf9-b8d8-4425-8645-e21af8addc0c.png)

**Comment by a-bouchat** [comment]
Whoa!!! That's nice :D

**Comment by dringeis** [comment]
Super cool!

**Comment by dringeis** [comment]
NIveau déformation ça donne quoi? (quand t'as une minute)

**Comment by mathieuslplante** [comment]
Ne sais pas encore. Je suis en train de faire les changements pour rouler le dataset, c'est un peu plus compliqué. Le code pour les frequency maps n'inclue pas le calcul des deformations.

**Comment by mathieuslplante** [comment]
Alex found an error in the code filtering the data. The corrected version has an even better coverage: 

![RCM_newData](https://github.com/a-bouchat/ice-tracker-deformations/assets/51676669/e2577172-3f97-459b-a16e-17dee81c8ded)

I am closing this issue now.
