### ISSUE TITLE
Data missing for S1

### ISSUE THREAD

**Issue by dringeis** [a-bouchat/ice-tracker-deformations#34]
we do not have data after april 2022 for S1.

Should we, or should we not, that is the question... :-/

**Comment by mathieuslplante** [comment]
Oui, il y a des fichiers tar que je dois transférer. Mais il y a un 25 jours en mai sans données. Je pense que c'est juste un petit bogue. Je vais demander à Mike.

**Comment by mathieuslplante** [comment]
Mike m'a envoyer les données manquantes, et j'ai ajouter toutes les données de 2022 sur dumbo. 

Je ferme l'issue.
