### ISSUE TITLE
Clean the output names

### ISSUE THREAD

**Issue by mathieuslplante** [a-bouchat/ice-tracker-deformations#4]
Self-explanatory

**Comment by a-bouchat** [comment]
Les noms de fichiers output sont maintenant harmonisés. Le format est: 
< satellite > + 'SID_' + < startdate > + '_' + < enddate > + '_' + 'dt' + < timestep > + '_tol' + < tolerance > + '_dx'

La seule chose qui reste à rajouter c'est la valeur du "dx" qui n'est pas encore déterminée, car les triangles ne sont pas encore filtrés par aire/taille.

Le mot "timestep" peu aussi porter à confusion car il s'agit de la résolution temporelle des déformations et non d'un time step itératif... on pourrait remplacer par "timeres" pour time resolution?
